services:
  # Application Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel_prod
      DB_USERNAME: laravel
      DB_PASSWORD: secretProd123
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    depends_on:
      - mariadb
      - redis
    networks:
      - internal
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`famproject.cloud`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=leresolver"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-public"

  # Base de données
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootProd123
      MYSQL_DATABASE: laravel_prod
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secretProd123
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal

  # Cache Redis
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - internal

  # Adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - internal
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`famproject.cloud`) && PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=leresolver"
      - "traefik.http.middlewares.adminer-strip.stripprefix.prefixes=/adminer"
      - "traefik.http.routers.adminer.middlewares=adminer-strip"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-public"

volumes:
  mariadb_data:

networks:
  internal:
  traefik-public:
    external: true
